package com.example.hacksecure

import android.util.Log

/**
 * Rule 2 – Port Analyzer (smart way).
 *
 * This file is completely independent from LocalVpnService and other existing files.
 * You can call PortAnalyzer.flagIfInsecurePort(...) from your packet-processing code
 * when you're ready, without modifying any of the existing logic right now.
 */

/**
 * Simple model for what you might show in the UI when an insecure port is detected.
 */
data class PortAlert(
    val protocol: String,
    val srcIp: String,
    val srcPort: Int,
    val dstIp: String,
    val dstPort: Int,
    val reason: String,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * In‑memory store that holds alerts generated by the port analyzer.
 * A future UI screen can read from PortAlertStore.getAlerts() to show them.
 */
object PortAlertStore {

    private val alerts = mutableListOf<PortAlert>()

    @Synchronized
    fun addAlert(alert: PortAlert) {
        alerts.add(alert)
        Log.w(
            "VPN_ENGINE",
            "PORT ALERT stored: ${alert.reason} | " +
                "proto=${alert.protocol} src=${alert.srcIp}:${alert.srcPort} " +
                "dst=${alert.dstIp}:${alert.dstPort}"
        )
    }

    @Synchronized
    fun getAlerts(): List<PortAlert> = alerts.toList()

    @Synchronized
    fun clear() {
        alerts.clear()
    }
}

/**
 * Core Rule 2 logic:
 *
 * - If we see dest or source port 80 (HTTP) or 21 (FTP),
 *   we DO NOT block the packet.
 * - Instead, we create a PortAlert and store it for the UI to display later,
 *   and also log a warning.
 */
object PortAnalyzer {

    // Ports we consider insecure / privacy‑sensitive
    private val insecurePorts = setOf(80, 21)

    /**
     * Apply Rule 2 for a single flow.
     *
     * Call this from your packet parsing code *after* you know:
     *  - protocol (e.g., "TCP" / "UDP")
     *  - srcIp / dstIp
     *  - srcPort / dstPort
     *
     * This helper does not throw; if ports are null or not in the list,
     * it simply does nothing.
     */
    fun flagIfInsecurePort(
        protocol: String,
        srcIp: String,
        srcPort: Int?,
        dstIp: String,
        dstPort: Int?
    ) {
        val sPort = srcPort ?: return
        val dPort = dstPort ?: return

        val matchedPorts = mutableListOf<Int>()
        if (sPort in insecurePorts) matchedPorts.add(sPort)
        if (dPort in insecurePorts && dPort != sPort) matchedPorts.add(dPort)

        if (matchedPorts.isEmpty()) return

        val reason = buildString {
            append("Insecure port detected (Rule 2): ")
            append(matchedPorts.joinToString(", ") { "port $it" })
            append(" – traffic likely unencrypted (HTTP/FTP)")
        }

        val alert = PortAlert(
            protocol = protocol,
            srcIp = srcIp,
            srcPort = sPort,
            dstIp = dstIp,
            dstPort = dPort,
            reason = reason
        )

        // Store for UI, and log for debugging
        PortAlertStore.addAlert(alert)
    }
}

